// Package types defines the API DTOs for newtcon-server's HTTP responses.
//
// This file defines the request and response shapes for POST /api/apply,
// matching API_CONTRACT.md §POST /api/apply (lines 2064–2223) and
// §Streaming substrate-operation events, PerWrite shape (lines 778–971).
package types

import "time"

// ApplyRequest is the body of POST /api/apply.
// API_CONTRACT.md §POST /api/apply request lines 2079–2083.
type ApplyRequest struct {
	// PreviewID references the preview generated by POST /api/preview.
	// A stale or unknown ID → 410 precondition_failure.
	PreviewID string `json:"preview_id"`
}

// ApplyResponse is the body of a successful POST /api/apply.
// API_CONTRACT.md §POST /api/apply response lines 2086–2123.
type ApplyResponse struct {
	// OperationID is the newtcon-minted operation identifier for this apply.
	OperationID string `json:"operation_id"`
	// PerTarget has one entry per applied target.
	PerTarget []PerTargetApply `json:"per_target"`
	// Aggregate summarises substrate outcomes across all targets.
	Aggregate ApplyAggregate `json:"aggregate"`
}

// PerTargetApply is the per-target slice of ApplyResponse.
// API_CONTRACT.md §POST /api/apply per_target shape lines 2091–2112.
type PerTargetApply struct {
	Node        string        `json:"node"`
	Interface   string        `json:"interface"`
	// Applied is true when newtron's batch-execute returned applied:true for
	// this target's per-Node bundle (the write LANDED in CONFIG_DB).
	// "applied:true does NOT imply verify passed" — API_CONTRACT.md lines 2194–2215.
	Applied     bool          `json:"applied"`
	IntentID    string        `json:"intent_id"`
	IntentURL   string        `json:"intent_url"`
	OperationID string        `json:"operation_id"`
	OperationURL string       `json:"operation_url"`
	// Pipeline traces the 4-stage pipeline (Intent → Replay → Render → Deliver).
	// v1 limitation: stage timestamps are all set to the apply-return time because
	// newtron's apply response does not expose per-stage timestamps.
	// TODO(post-ship): populate per-stage timestamps when newtron exposes them.
	Pipeline    Pipeline      `json:"pipeline"`
	// Verify is the Device I/O assertion per unified-pipeline-architecture §7.
	// "Verify is a Device I/O operation, not a pipeline stage."
	Verify      VerifyAssertion `json:"verify"`
	// PerWrite is the per-substrate-operation sequence newtron executed for this
	// target, ordered by seq. Each entry is a PerWrite per §Streaming substrate-
	// operation events. Operator-philosophy invariant #1 (no black boxes) +
	// Concrete success vision point 1: operator sees each substrate write as it lands.
	PerWrite    []PerWrite    `json:"per_write"`
	Confidence  Confidence    `json:"confidence"`
}

// Pipeline traces the 4-stage newtron pipeline.
// API_CONTRACT.md §POST /api/apply pipeline shape lines 2099–2104.
// Stage values: "pending | in_progress | complete | failed | skipped".
type Pipeline struct {
	Intent  PipelineStage `json:"intent"`
	Replay  PipelineStage `json:"replay"`
	Render  PipelineStage `json:"render"`
	Deliver PipelineStage `json:"deliver"`
}

// PipelineStage is one stage in the pipeline trace.
// API_CONTRACT.md §GET /api/operations/{operation_id} pipeline field rules.
type PipelineStage struct {
	Stage string    `json:"stage"`
	At    time.Time `json:"at"`
}

// VerifyAssertion is the Device I/O assertion result.
// API_CONTRACT.md §POST /api/apply verify shape lines 2105–2109 and
// §GET /api/operations/{operation_id} verify field rules lines 3479–3539.
type VerifyAssertion struct {
	// Kind is always "device_io_assertion" per contract line 2106.
	Kind   string `json:"kind"`
	// State is "pending | in_progress | complete | failed | skipped".
	State  string `json:"state"`
	// Assertion is populated when State == "complete" or State == "failed".
	Assertion  *VerificationAssertionDTO `json:"assertion,omitempty"`
	Confidence Confidence                `json:"confidence"`
}

// VerificationAssertionDTO carries the verify assertion result.
// API_CONTRACT.md §GET /api/operations/{operation_id} assertion shape
// lines 3432–3445 and verify-failure path per newtron#21.
type VerificationAssertionDTO struct {
	Passed int                    `json:"passed"`
	Failed int                    `json:"failed"`
	Errors []VerificationErrorRow `json:"errors"`
}

// VerificationErrorRow describes one verify assertion failure.
// API_CONTRACT.md §GET /api/operations/{operation_id} errors[] lines 3435–3444.
// device_response is the verbatim device-side reply — per operator-philosophy
// invariant #7 ("Errors carry the substrate") and §14 ("Verify Your Writes"):
// a friendly summary that loses the substrate is a teaching failure.
type VerificationErrorRow struct {
	Table          string `json:"table"`
	Key            string `json:"key"`
	Field          string `json:"field"`
	Expected       string `json:"expected"`
	Actual         string `json:"actual"`
	DeviceResponse string `json:"device_response"`
}

// PerWrite is one substrate operation newtron performed against a device.
// API_CONTRACT.md §Streaming substrate-operation events, PerWrite shape
// lines 778–971. Used in both the JSON variant (per_target[*].per_write[])
// and the SSE variant (substrate_op events). Both carry the same shape per
// API_CONTRACT.md lines 2153–2156.
//
// This is the operationalization of operator-philosophy invariant #1 (no black
// boxes) + invariant #2 (manual-mode parity) + the Concrete success vision
// points 1–3: the operator sees each substrate write as it lands, sees exactly
// which write failed with the verbatim device response, and can copy-paste
// cli_command into their own ssh session to reproduce the operation.
type PerWrite struct {
	// Seq is the zero-based ordinal within the per-target apply sequence.
	// API_CONTRACT.md line 819.
	Seq int `json:"seq"`
	// OperationID is the newtcon operation_id for this per-target apply.
	// Same value as PerTargetApply.OperationID.
	OperationID string `json:"operation_id"`
	// Target is the {network, node, interface} triple.
	Target PerWriteTarget `json:"target"`
	// Kind is bounded: "redis_write | redis_delete | daemon_wait | verify_read".
	Kind string `json:"kind"`
	// Substrate locates the CONFIG_DB entry the op acted on.
	Substrate *PerWriteSubstrate `json:"substrate"`
	// Result is "applied | rejected | skipped".
	Result string `json:"result"`
	// CLICommand is the exact command the operator would type against the device
	// to reproduce this substrate operation by hand. Per operator-philosophy
	// invariant #2 (manual-mode parity): newtcon teaches the device-level
	// equivalent. API_CONTRACT.md lines 876–894.
	CLICommand string `json:"cli_command"`
	// DeviceResponse is the verbatim wire reply from the device. NEVER
	// paraphrased. Per invariant #7 and DESIGN_PRINCIPLES_NEWTRON §14.
	// For verify_read failures: the full HGETALL content as key=value pairs.
	// For redis_write success: typically "(integer) N" or "OK".
	DeviceResponse string `json:"device_response"`
	// At is RFC 3339 UTC with millisecond precision.
	At time.Time `json:"at"`
	// RationaleRef anchors each per-write entry to its substrate cause and principle.
	// API_CONTRACT.md line 918: REQUIRED.
	RationaleRef RationaleRef `json:"rationale_ref"`
	// Source is always nil in v1 per API_CONTRACT.md lines 929–970.
	// Reserved for call-site provenance {call_site, function} — deferred
	// indefinitely per newtron#12. Consumers MUST tolerate null.
	// TODO(post-ship): populate when newtron#12 re-evaluation trigger fires.
	Source *struct{} `json:"source"`
}

// PerWriteTarget is the {network, node, interface} triple for a PerWrite entry.
// API_CONTRACT.md §PerWrite shape target field lines 830–836.
type PerWriteTarget struct {
	Network   string `json:"network"`
	Node      string `json:"node"`
	Interface string `json:"interface,omitempty"`
}

// PerWriteSubstrate locates the CONFIG_DB entry a substrate op acted on.
// API_CONTRACT.md §PerWrite shape substrate field lines 851–854.
type PerWriteSubstrate struct {
	Table  string         `json:"table"`
	Key    string         `json:"key"`
	Fields map[string]any `json:"fields"`
}

// ApplyAggregate summarises substrate outcomes across all applied targets.
// API_CONTRACT.md §POST /api/apply aggregate shape lines 2114–2122.
//
// The four total_* counters expose substrate-operation totals at a glance per
// operator-philosophy invariant #1 — "the operator's first view is not 'applied:
// true on 3 targets' but '21 substrate writes landed, 2 daemon waits, 14 verify
// reads passed'." API_CONTRACT.md lines 2177–2187.
type ApplyAggregate struct {
	AllApplied          bool       `json:"all_applied"`
	VerifyPending       int        `json:"verify_pending"`
	TotalWritesLanded   int        `json:"total_writes_landed"`
	TotalWritesRejected int        `json:"total_writes_rejected"`
	TotalDaemonWaits    int        `json:"total_daemon_waits"`
	TotalVerifyReadsFailed int     `json:"total_verify_reads_failed"`
	Confidence          Confidence `json:"confidence"`
}
